plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/ronri/Documents/Codex/2026-06-08/https-serene-pothos-6e4358-netlify-app/deploy"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]