headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/ronri/Documents/Codex/2026-06-08/https-serene-pothos-6e4358-netlify-app/deploy"
publishOrigin = "config"
base = "/Users/ronri/Documents/Codex/2026-06-08/https-serene-pothos-6e4358-netlify-app/deploy"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"